version: '3.7'

services:
  radicale:
    image: "\
      tomsquest/docker-radicale@sha256:\
      8b50b8c664d9557e47f723e18064d8f5f822e39d4e8a3d2385947ee13a2f8222\
    "  # 3.4.1.0
    container_name: radicale
    restart: on-failure
    volumes:
      - .volumes/data:/data

networks:
  default:
    name: ${SWAG_NETWORK}
    external: true
