version: "2.1"
services:

  wireguard-gluetun-internal:
    image: "\
      linuxserver/wireguard@sha256:\
      c095b08123345cefa1a8a589a417c56690c046ba925d292f4657f3fefcce1dfd\
    "  # 1.0.20210914
    container_name: wireguard-gluetun-internal
    network_mode: service:wireguard-gluetun
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    env_file:
      - .env-files/wireguard.env
      - .env-files/linuxserverio.env
    environment:
      - SERVERURL=${DUCKDNS_SUBDOMAIN}.duckdns.org
      - SERVERPORT=${WIREGUARD_GLUETUN_SERVERPORT}
      - INTERNAL_SUBNET=${WIREGUARD_NETWORK_SUBNET}
      # Tunnel everything through vpn
      - ALLOWEDIPS=0.0.0.0/1,128.0.0.0/1
      # Ref: https://github.com/linuxserver/docker-wireguard/issues/62#issuecomment-2010533285
      - USE_COREDNS=false
    volumes:
      - .volumes/config:/config
    depends_on:
      - wireguard-gluetun
    restart: on-failure

  # We use dnsmasq instead of wireguard's built-in coredns
  # By hosting DNS server in the same gluetun container we tunnel queries through VPN
  wireguard-gluetun-internal-dnsmasq:
    image: "\
      strm/dnsmasq@sha256:\
      dcf4c0aeb69ea6b9bca81314449d732ecd2ea021588d8a34d4be7c2304f89a39\
    "  # latest, just one release in years
    container_name: wireguard-gluetun-internal-dnsmasq
    network_mode: service:wireguard-gluetun-internal
    cap_add:
      - NET_ADMIN
    volumes:
      - .volumes/dnsmasq.conf:/etc/dnsmasq.conf
    depends_on:
      - wireguard-gluetun-internal
    restart: on-failure

  wireguard-gluetun:
    image: "\
      qmcgaw/gluetun@sha256:\
      7b9fbfc187e7603d0039bf777ea4b278409e42f6d038c02deb14727153591ac5\
    "  # TODO: update and fix incompatibility with current wireguard iptables setup
    container_name: wireguard-gluetun
    cap_add:
      - NET_ADMIN
    env_file:
      - .env-files/gluetun.env
    environment:
      # No DNS over TLS as that would clash with dnsmasq
      - DOT=off
      # Allow access to host local network
      - FIREWALL_OUTBOUND_SUBNETS=${HOST_NETWORK_SUBNET}
      # Expose health service externally
      - HEALTH_SERVER_ADDRESS=0.0.0.0:9999
    ports:
      - ${WIREGUARD_GLUETUN_SERVERPORT}:51820/udp
    volumes:
      - .volumes/gluetun:/gluetun
    restart: on-failure

networks:
  default:
    name: ${MAIN_NETWORK}
    external: true
