version: '3.4'
services:
  vaultwarden:
    image: "\
      vaultwarden/server@sha256:\
      63cce7624f655f83ad5bab66ef62bc3e3327116b068704bfbbda5d0c1b3003be\
    "  # 1.33.2-alpine
    container_name: vaultwarden
    env_file:
      - .env-files/private.env
    environment:
      - WEBSOCKET_ENABLED=true
    volumes:
      - .volumes/data:/data
    restart: on-failure

networks:
  default:
    name: ${SWAG_NETWORK}
    external: true
