version: "2.1"
services:
  jellyfin:
    image: "\
      linuxserver/jellyfin@sha256:\
      7cdcd4b6b60765290af7a2740960ce30c1f5548313ae60f7e23f6995ed4d147e\
    "  # 10.10.5
    container_name: jellyfin
    env_file:
      - .env-files/linuxserverio.env
    ports:
      - 8096:8096
    volumes:
      - .volumes/config:/config
      - ${MEDIA_VOLUME}/movies:/data/movies
      - ${MEDIA_VOLUME}/shows:/data/shows
    restart: on-failure

networks:
  default:
    name: ${SWAG_NETWORK}
    external: true
