#!/bin/sh

set -eu

root="$(dirname "$(realpath "$0")")/..root"

deployment_path="$root/deployment"

if [ ! -d "$(realpath "$deployment_path")" ]; then
    >&2 echo Error: deployment not setup
    exit 1
fi

echo 'This requires sudo permission, validate to proceed'
sudo -v

backups_path="$deployment_path/.backups"
backup_path="$backups_path/$(date +%Y%m%d_%H%M%S)"
mkdir -p "$backup_path"
echo "Backing up existing files in $backup_path"

env_source_path="$root/apps/.env"
env_target_path="$deployment_path/.env"
if [ -e "$env_target_path" ]; then
    mv "$env_target_path" "$backup_path"
fi
cp -r "$env_source_path" "$env_target_path"

breadcrumb_source_path="$root/apps/..apps"
breadcrumb_target_path="$deployment_path/..apps"
if [ -e "$breadcrumb_target_path" ]; then
    mv "$breadcrumb_target_path" "$backup_path"
fi
cp -P "$breadcrumb_source_path" "$breadcrumb_target_path"

startup_source_path="$root/apps/startup"
startup_target_path="$deployment_path/startup"
if [ -e "$startup_target_path" ]; then
    mv "$startup_target_path" "$backup_path"
fi
cp "$startup_source_path" "$startup_target_path"

startup_service_source_path="$root/startup@.service"
startup_service_target_path='/etc/systemd/system/selfhost-startup@.service'
if [ -e "$startup_service_target_path" ]; then
    sudo mv "$startup_service_target_path" "$backup_path"
fi
sudo cp "$startup_service_source_path" "$startup_service_target_path"
sudo systemctl enable "selfhost-startup@$USER.service"
