version: "2.1"
services:
  duckdns:
    image: "\
      linuxserver/duckdns@sha256:\
      47db61f0b95d25259bef42002c266bbea181b10f8542ae5fed76235ff2a443ff\
    "  # version-04546c3e
    container_name: duckdns
    env_file:
      - .env-files/linuxserverio.env
    environment:
      - SUBDOMAINS=${DUCKDNS_SUBDOMAIN}  # comma-separated list
      - TOKEN=${DUCKDNS_TOKEN}
      - LOG_FILE=true
    volumes:
      - .volumes/config:/config
    restart: on-failure
